# -*- coding: utf-8 -*-
"""GPT-2-FineTuning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XSsoz4f0CtJJku-YdWk8CrLa7VFUQWAk
"""

!pip install transformers datasets accelerate torch -U

from datasets import Dataset, load_dataset

train_ds = load_dataset("ScaleAI/SWE-Atlas-QnA")

train_ds

from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = 'gpt2'

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(model_name)

def tokenize(examples):
  tokens = tokenizer(
      examples['prompt'],
      truncation=True,
      padding='max_length',
      max_length=512
  )
  tokens['reference_answer']=tokens['input_ids'].copy()
  return tokens

tokenized_ds = train_ds.map(tokenize, batched=True, remove_columns=['task_id','repository_url','repository_base_commit','language','category','rubric','docker_image'])
tokenized_ds.set_format('torch')

split = tokenized_ds['test'].train_test_split(test_size=0.1, seed=42)

train_ds = split["train"]  # ← extract explicitly
val_ds   = split["test"]

split['train']

from transformers import TrainingArguments

training_args = TrainingArguments(
    num_train_epochs=10,
    per_device_train_batch_size=4,
    learning_rate=1e-3,
    logging_steps=4,
    fp16=True,
    report_to=[]
    )

from transformers import Trainer,DataCollatorForLanguageModeling
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    data_collator=DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)
)

trainer.train()

from transformers import pipeline

generator = pipeline("text-generation", model=model,tokenizer=tokenizer)
output = generator("Grafana", max_new_tokens=100, do_sample=True)
print(output[0]["generated_text"])

